### ISSUE TITLE
Kesalahan pada signup_closed_button

### ISSUE THREAD

**Issue by realodix** [fransallen/flarum-ext-indonesian#3]
Mohon maaf, Saya menemukan kesalahan penulisan string pada repository Saya, dan Saya juga menemukannya di repository Anda.

Pada [fransallen/flarum-ext-indonesian/core.yml#L234](https://github.com/fransallen/flarum-ext-indonesian/blob/master/locale/core.yml#L234)

Harusnya `signup_closed_button`, bukan `signup_open_button`

**Comment by fransallen** [comment]
Fixed. Terima kasih. Saya belum sempat ngecek flarum sih.
